services:
  db:
    image: postgres:17
    restart: always
    env_file:
      - myprofile_backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./myprofile_backend
    container_name: django-backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8017
    restart: always
    env_file:
      - myprofile_backend/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8017:8000"
    volumes:
      - ./myprofile_backend:/app
      - media_volume:/app/media

  frontend:
    build: ./frontend
    container_name: react-frontend
    restart: always
    env_file:
      - frontend/.env
    volumes:
      - frontend_build:/app/dist

volumes:
  postgres_data:
  frontend_build:
  media_volume: