# Generated by Django 5.2.6 on 2026-02-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.JSONField(),
        ),
    ]
