name: Deploy Django + React

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

        run: |
          sshpass -p "$SSH_PASSWORD" ssh \
            -o StrictHostKeyChecking=no \
            $SSH_USER@$SSH_HOST << 'EOF'

          cd /projects/myprofile

          echo "Pull latest code..."
          git pull origin main

          echo "Stopping containers..."
          docker compose down

          echo "Building and starting containers..."
          docker compose up -d --build

          echo "Running migrations..."
          docker compose exec -T backend python manage.py migrate

          echo "Collecting static files..."
          docker compose exec -T backend python manage.py collectstatic --noinput

          echo "Deployment completed successfully 🚀"

          EOF